In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.tree import DecisionTreeClassifier

In [4]:
df = pd.read_csv("yeast.csv")
df.head(3)

    mcg   gvh   alm   mit  erl  pox   vac   nuc name
0  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22  MIT
1  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22  MIT
2  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22  MIT

In [14]:
len(df["name"].unique()) # so there are 10 unique classification values....

10

In [5]:
# Since model cannot read string data in name column, encoding it...
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["class"] = le.fit_transform(df["name"])

In [6]:
df.head(3)

    mcg   gvh   alm   mit  erl  pox   vac   nuc name  class
0  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22  MIT      6
1  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22  MIT      6
2  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22  MIT      6

In [16]:
X = df.drop(columns=["name","class"]).values
y = df["class"].values

In [17]:
dt = DecisionTreeClassifier(criterion='gini',max_depth=None,min_samples_split=2,random_state=42)

In [18]:
# Applying Cross-Validation..
from sklearn.model_selection import StratifiedKFold, cross_val_predict

In [19]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [20]:
y_pred = cross_val_predict(dt,X,y,cv=cv)

In [21]:
y_prob = cross_val_predict(dt,X,y,cv=cv,method='predict_proba')

In [22]:
# Evalutaing my model...
from sklearn.metrics import f1_score,recall_score,matthews_corrcoef,roc_auc_score

In [26]:
f1 = f1_score(y,y_pred,average='weighted')
print("F1 Score: ",f1)

F1 Score:  0.5061344377251119

In [27]:
recall = recall_score(y, y_pred, average="macro")
print("Recall: ", recall)

Recall:  0.3711899061287813

In [28]:
mcc = matthews_corrcoef(y, y_pred)
print("Matthews Correlation Coefficient: ", mcc)

Matthews Correlation Coefficient:  0.36051992831290813

In [29]:
auc = roc_auc_score(y, y_prob, multi_class="ovr")
print("ROC AUC: ",auc)

ROC AUC:  0.6532043165860719